### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [ ]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. How can you get help on `np.array`?

Call `dir()` on `np.array`. 

Call `dir()` on `car`.

Note the difference. `car` has methods and attributes we can use.

In [ ]:
#You can use the help() function, or ?:
#help(np.array)
#?np.array

#dir(np.array)
dir(car)

2. What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [ ]:
#The numpy data types
print("The car data type is: " + str(car.dtype))
print("The mpg data type is: " + str(mpg.dtype))
print("The horsepower data type is: " + str(horsepower.dtype))
print("The origin data type is: " + str(origin.dtype))


3. `numpy` is often imported as `np`. What is this action called? Why might you do this? 

"np" is an alias for numpy. We use aliasing to make writing the code easier - why use 5 characters when 2 will do?

4. Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [ ]:
print("The size of the car array is: " + str(car.ndim))
print("The size of the mpg array is: " + str(mpg.ndim))
print("The size of the cylinders array is: " + str(cylinders.ndim))

5. Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [ ]:
#Question - why do some of these cars have mpg = 0? I checked the original data set and the entries are correct. They seem to be discontinued models of cars. Seems strange.
mpg*12
mpg/3
mpg**4
np.sqrt(mpg)

6. What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [ ]:
from scipy import stats

print("The sum of the array horsepower is: " + str(np.sum(horsepower)))
print("The min of the array horsepower is: " + str(np.min(horsepower)))
print("The max of the array horsepower is: " + str(np.max(horsepower)))
print("The median of the array horsepower is: " + str(np.median(horsepower)))
print("The mode of the array horsepower is: " + str(stats.mode(horsepower)))

#For the output of stats.mode, the mode value is the most frequent value, and the count is the number of times that value occurs in the array.

7. Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [ ]:
print(acceleration[:5])

#We use numpy.array[start:stop:step] to subsample every nth element in an array. Here I am using a modification that makes a copy of the array. That way, I won't change the original.
print(acceleration[::2].copy())


8. Show how to select the number `99` in the array below. 

In [ ]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

In [ ]:
select_99[1,2]

9. Select the last element in each subarray (do this with one operation.)

In [ ]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [ ]:
select_more[:,2]

10. Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [ ]:
#np.lookfor('log')
np.log(mpg)

11. You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [44]:
#type(origin)

np.unique(origin)
# Question- why is the output giving the data type of the object "origin"?

array(['Europe', 'Japan', 'US'], dtype=object)

12. 
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [51]:
twodarray = np.array([[1,2],[2,3]])
print(twodarray.ndim)
print(twodarray.shape)
threedarray = np.array([[[0,0],[0,1]],[[1,0],[1,1]]])
print(threedarray.ndim)
print(threedarray.shape)
fourdarray = np.array([[[[0,1,2],[2,1,0]]],[[[1,1,2],[2,1,1]]],[[[0,1,2],[2,1,0]]],[[[1,1,2],[2,1,1]]]])
print(fourdarray.ndim)
print(fourdarray.shape)

2
(2, 2)
3
(2, 2, 2)
4
(4, 1, 2, 3)


13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [52]:
origin == 'US'

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

14. Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [53]:
car[origin == 'US']

array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

7. Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

Calculations with numpy arrays are MUCH faster!

If you need to have mixed data types stored together, you would have to use a list, as arrays, by definitions, are objects with homogeneous data types.

1.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

In [54]:
#An identity matrix is a square, n-dimensional matrix with the element "1" on the diagonal and zeroes everywhere else.
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

2. Transpose the following array. 

In [55]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
np.transpose(transpose_me)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

3. Why does this multiplication operation fail? 

In [65]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

print(arr1.shape)
print(arr2.shape)

#none of these work:
#arr1 * arr2

#arr2 * arr1
#arr1 * np.transpose(arr2)

(3, 3)
(2, 3)


ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

This multiplication fails because the shapes are different. 
At the outset it looks like it violates the rules of matrix multiplication: arr1 is a 3x3 matrix, and arr2 is a 2x3 matrix. 
In order to left-multiply an mxn matrix with an nxp matrix, the "n" has to be the same. In this case, they are not.
However, one should be able to reverse the order of multiplication and get a result: arr2*arr1. 
However, you do not. So it must be a numpy thing and not a linear algebra thing. 
(NB arr1*arr2 != arr2*arr1 in most cases)

Use numpy to answer the following questions. 

4. What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

In [72]:
#origin == "Europe"
#horsepower[origin == "Europe"]
print("The average horsepower for European cars is: " + str(np.mean(horsepower[origin == "Europe"])))

The average horsepower for European cars is: 78.78082191780823


5. On average are Japanse cars more fuel efficient than US cars? 

So here's the straightforward way to do it:

In [74]:
print("The average fuel economy of Japanese cars is: " + str(np.mean(mpg[origin == "Japan"])))
print("The average fuel economy of domestic cars is: " + str(np.mean(mpg[origin == "US"])))

The average fuel economy of Japanese cars is: 30.450632911392404
The average fuel economy of domestic cars is: 19.688188976377955


You can look at the results and see, clearly, that the answer is "yes". However, I wanted to see if there's a bit more streamlined way to answer this question, making a comparison:

In [76]:
np.mean(mpg[origin == "Japan"]) > np.mean(mpg[origin == "US"])

True

I like this approach better!

6. What is the correlation coefficient of `mpg` and `weight`?

In [67]:
np.corrcoef(mpg,weight)

array([[ 1.        , -0.78750994],
       [-0.78750994,  1.        ]])